export const regionData = [
  {
    value: "all",
    label: "All Regions",
    query: [
      "TotalAsiaPacific",
      "TotalNorthAmerica",
      "TotalCIS",
      "TotalMiddleEast",
      "TotalEurope",
      "TotalAfrica",
      "TotalEU",
      "TotalS.&Cent.America",
      "TotalWorld",
    ],
  },
  {
    value: "northAmerica",
    label: "North America",
    query: ["Canada", "Mexico", "US"],
  },
  {
    value: "southCentral",
    label: " South & Central America",
    query: [
      "Peru",
      "Ecuador",
      "Bolivia",
      "Chile",
      "Trinidad&Tobago",
      "Cuba",
      "Brazil",
      "Argentina",
      "Venezuela",
      "Curacao",
      "NetherlandsAntilles",
      "Colombia",
    ],
  },
{
    value: "europe",
    label: "Europe",
    query: [
        "Belgium",
        "Latvia",
        "Austria",
        "Greece",
        "France",
        "Sweden",
        "Ukraine",
        "Luxembourg",
        "NorthMacedonia",
        "Italy",
        "Bulgaria",
        "Iceland",
        "Ireland",
        "Germany",
        "Romania",
        "Denmark",
        "Poland",
        "Slovakia",
        "Estonia",
        "Portugal",
        "Lithuania",
        "Serbia",
        "Netherlands",
        "Hungary",
        "Switzerland",
        "UnitedKingdom",
        "Spain",
        "Turkiye",
        "Cyprus",
        "Finland",
        "CzechRepublic",
        "Slovenia",
        "Croatia",
        "Norway"
    ]
},
  {
    value: "cis",
    label: "Commonwealth of Independent States (CIS)",
    query: [
      "Belarus",
      "RussianFederation",
      "Kazakhstan",
      "Azerbaijan",
      "Turkmenistan",
      "USSR",
      "Uzbekistan",
    ],
  },
  {
    value: "middleEast",
    label: "Middle East",
    query: [
      "Yemen",
      "SaudiArabia",
      "Qatar",
      "Kuwait",
      "Iraq",
      "Iran",
      "Israel",
      "Bahrain",
      "Syria",
      "UnitedArabEmirates",
      "Oman",
    ],
  },
  {
    value: "africa",
    label: "Africa",
    query: [
      "Libya",
      "RepublicofCongo",
      "Tunisia",
      "Zimbabwe",
      "Sudan",
      "Chad",
      "Egypt",
      "Madagascar",
      "Angola",
      "SouthSudan",
      "DemocraticRepublicofCongo",
      "Morocco",
      "Mozambique",
      "SouthAfrica",
      "Nigeria",
      "Algeria",
      "EquatorialGuinea",
      "Zambia",
      "Gabon",
    ],
  },
  {
    value: "asiaPacific",
    label: "Asia Pacific",
    query: [
      "PapuaNewGuinea",
      "Philippines",
      "Australia",
      "SouthKorea",
      "Thailand",
      "Japan",
      "India",
      "ChinaHongKongSAR",
      "Pakistan",
      "Brunei",
      "SriLanka",
      "Myanmar",
      "Taiwan",
      "Malaysia",
      "Singapore",
      "Mongolia",
      "Indonesia",
      "NewZealand",
      "Vietnam",
      "China",
      "Bangladesh",
      "NewCaledonia",
    ],
  },
];
export const countryMapping = {
  southCentral: [
    {
      value: "argentina",
      label: "Argentina",
    },
    {
      value: "bolivia",
      label: "Bolivia",
    },
    {
      value: "brazil",
      label: "Brazil",
    },
    {
      value: "chile",
      label: "Chile",
    },
    {
      value: "colombia",
      label: "Colombia",
    },
    {
      value: "cuba",
      label: "Cuba",
    },
    {
      value: "curacao",
      label: "Curacao",
    },
    {
      value: "ecuador",
      label: "Ecuador",
    },
    {
      value: "netherlands-antilles",
      label: "Netherlands Antilles",
    },
    {
      value: "peru",
      label: "Peru",
    },
    {
      value: "trinidad-tobago",
      label: "Trinidad & Tobago",
    },
    {
      value: "venezuela",
      label: "Venezuela",
    },
  ],
  northAmerica: [
    { value: "unitedStates", label: "United States" },
    { value: "canada", label: "Canada" },
    { value: "mexico", label: "Mexico" },
    // Agrega más países de Norteamérica aquí
  ],
};